/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#3a302a',
        'on-tertiary-fixed': '#2e1515',
        'on-secondary-container': '#605850',
        'surface-variant': '#ece6dc',
        'inverse-primary': '#f0a878',
        'inverse-on-surface': '#faf5ee',
        'on-secondary-fixed': '#2a2420',
        'on-error-container': '#7a1a10',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        tertiary: '#8c3c3c',
        'on-primary-fixed-variant': '#8a4518',
        'surface-container-highest': '#e6e0d6',
        secondary: '#78706a',
        'on-surface-variant': '#605850',
        'surface-container-lowest': '#ffffff',
        primary: '#c2652a',
        'surface-tint': '#c2652a',
        'on-background': '#3a302a',
        'surface-container': '#f2ece4',
        'surface-bright': '#faf5ee',
        'secondary-container': '#eae2da',
        'on-tertiary-fixed-variant': '#6e3030',
        background: '#faf5ee',
        'surface-dim': '#dcd6cc',
        'secondary-fixed-dim': '#cec6be',
        error: '#c0392b',
        'surface-container-low': '#f6f0e8',
        'secondary-fixed': '#eae2da',
        'primary-container': '#e08850',
        'on-primary-fixed': '#401a08',
        'primary-fixed-dim': '#f0a878',
        'on-tertiary-container': '#3a2020',
        'on-primary-container': '#fbe8d8',
        'on-secondary-fixed-variant': '#504840',
        'error-container': '#fce4e0',
        'on-surface': '#3a302a',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#fce0e0',
        'primary-fixed': '#fbe8d8',
        'tertiary-fixed-dim': '#e8a0a0',
        'tertiary-container': '#d47070',
        'surface-container-high': '#ece6dc',
        surface: '#faf5ee',
        'on-secondary': '#ffffff',
        'outline-variant': '#d8d0c8',
        outline: '#9a9088',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"EB Garamond"', 'serif'],
        display: ['"EB Garamond"', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
